import type { CatCaptionResponse, ClimbAnalysisResponse } from '../types'

export const catCaptionFallbacks: CatCaptionResponse[] = [
  {
    catName: 'Director Whiskers',
    professionalTitle: 'Chief Nap Strategist',
    caption: "Thrilled to announce that after 14 hours of rigorous stakeholder alignment (sleep), I've successfully onboarded the left armrest as a permanent collaborative workspace. Q4 nap metrics are ahead of forecast. The couch has accepted my terms. #OpenToOpportunities",
    hashtags: ['#NapStrategy', '#WorkspaceOptimization', '#ThoughtLeadership'],
    rivalryMention: 'Special acknowledgment to Mittens for her unsolicited feedback during the 2pm window.',
    celebrationReason: 'Successful territory expansion into previously disputed blanket zone',
  },
  {
    catName: 'VP Fluffington',
    professionalTitle: 'Senior Treaty Negotiator',
    caption: "Excited to share that the Southeastern Windowsill Peace Accord has entered its 72nd hour without incident. Both parties have agreed to a shared bird-watching framework pending further review. This is what collaborative disruption looks like. I am humbled. 🐾",
    hashtags: ['#TreatyViolation', '#WindowsillDiplomacy', '#StrategicYearning'],
    rivalryMention: "Grateful for the feedback from Biscuit, even if it arrived at 3am and consisted entirely of knocking over my water glass.",
    celebrationReason: 'First successful bi-lateral nap summit in recorded history',
  },
  {
    catName: 'Ceo Biscuit',
    professionalTitle: 'Executive Blanket Relocator',
    caption: "After extensive due diligence, I have made the difficult decision to relocate the primary thermal asset (the good blanket) to my corner of the couch. This was not a decision I made lightly. All affected stakeholders have been notified via meow. Change is difficult. Growth is messier.",
    hashtags: ['#StrategicRelocation', '#ThermalAssetManagement', '#ExecutiveDecision'],
    rivalryMention: 'I want to be transparent: this decision was partially motivated by the fence incident last Tuesday.',
    celebrationReason: 'Blanket relocation completed under budget (zero calories expended)',
  },
  {
    catName: 'Principal Mittens',
    professionalTitle: 'Independent Fence Consultant',
    caption: "I've been quietly building something incredible for the past six months. Today, I'm proud to announce I have achieved 100% coverage of the northwest fence line by 9:47am. The data doesn't lie. The birds know. The squirrels are concerned. I remain available for comment.",
    hashtags: ['#FenceLineDispute', '#TerritoryExpansion', '#EarlyMover'],
    rivalryMention: 'No comment on the Orangecat situation at this time.',
    celebrationReason: 'Personal record for consecutive hours of strategic fence presence',
  },
  {
    catName: 'Director Noodle',
    professionalTitle: 'Passive-Aggressive Stakeholder Lead',
    caption: "Grateful for the feedback I received this morning regarding my performance. I have reviewed the concerns (knocking my water bowl over, sitting on the laptop) and determined they are not aligned with my core competencies. I will be escalating this through the appropriate channels (staring). We move forward.",
    hashtags: ['#FeedbackCulture', '#ManagingUp', '#RadicalTransparency'],
    rivalryMention: 'This is not directed at anyone in particular.',
    celebrationReason: 'Successfully escalated three separate incidents before breakfast',
  },
  {
    catName: 'Senior Analyst Floofus',
    professionalTitle: 'Under-Couch Innovation Director',
    caption: "Pleased to report that after a 47-minute exploratory session, I have confirmed the presence of a previously unmapped dust bunny ecosystem under the couch. This represents a significant opportunity. I have assembled a cross-functional team (myself) to evaluate strategic options. The quarterly pounce report will follow.",
    hashtags: ['#Innovation', '#UndercouchEconomy', '#DiscoveryMindset'],
    rivalryMention: 'Shoutout to the under-bed team for their continued territorial discipline.',
    celebrationReason: 'Dust bunny discovery exceeds internal expectations by 400%',
  },
  {
    catName: 'COO Patches',
    professionalTitle: 'Chief Operational Napper',
    caption: "I'm not saying I reinvented the afternoon nap. But I'm not NOT saying that. Today marks 2,000 consecutive hours of nap output. The metrics speak for themselves. My team has been exceptional. My pillow has been exceptional. The sunbeam arrives at 2:47pm daily — I have leveraged this aggressively.",
    hashtags: ['#AdvancedNapping', '#PerformanceMetrics', '#Grindset'],
    rivalryMention: 'Deeply inspired by Biscuit, though I maintain our nap philosophies differ fundamentally.',
    celebrationReason: 'Nap quality index reached historic high of 9.8/10',
  },
  {
    catName: 'Managing Director Crumbs',
    professionalTitle: 'Executive Keyboard Supervisor',
    caption: "A humble update: I have spent the last three hours ensuring this keyboard remains properly warmed. Productivity is a team sport. The human is technically capable of working around me, but I believe in servant leadership. I am the servant. The keyboard is my leader. Please send treats.",
    hashtags: ['#ServantLeadership', '#KeyboardGovernance', '#WorkplaceInnovation'],
    rivalryMention: 'Cannot confirm or deny allegations regarding the deleted emails.',
    celebrationReason: 'Keyboard temperature maintained at optimal occupancy levels for 12 consecutive hours',
  },
  {
    catName: 'Chief Mrowlings',
    professionalTitle: 'Senior Midnight Vocal Strategist',
    caption: "At 3:14am, I delivered what I believe to be the most impactful vocal performance of Q2. The audience (sleeping humans) initially failed to appreciate the nuance. By 3:18am, full buy-in had been achieved. I then ate their food. This is what peak stakeholder management looks like. I'm available to consult.",
    hashtags: ['#MidnightStrategy', '#VocalLeadership', '#StakeholderAlignment'],
    rivalryMention: 'The dog was not present, which is why the presentation succeeded.',
    celebrationReason: 'Secured 100% of available cat food before dawn',
  },
  {
    catName: 'Director Whiskers',
    professionalTitle: 'Territorial Account Manager',
    caption: "Update from the sun patch front: after several weeks of joint occupancy exploration, both parties have agreed this isn't working. I have taken full control of the south-facing window. Orangecat has been offered a settlement (the bathroom). He has not yet responded. My lawyers (paws) are ready.",
    hashtags: ['#TerritoryManagement', '#SunPatchAlliance', '#LegallyDistinct'],
    rivalryMention: 'Orangecat, the ball is in your court. Or rather, the sun patch is in my window.',
    celebrationReason: 'Dispute resolution completed without formal incident escalation',
  },
  {
    catName: 'Principal Advisor Boop',
    professionalTitle: 'Head of Vibe Curation',
    caption: "Closing out the week with deep gratitude. I knocked over exactly four things that had been in the same spot for years. It was time. Change is hard. Change is necessary. Change is when I push your coffee off the counter because I wanted to see what would happen. Growth mindset.",
    hashtags: ['#VibeCuration', '#ChangeAgent', '#GrowthMindset'],
    rivalryMention: 'This was inspired by a TED talk I watched while sitting on the remote.',
    celebrationReason: 'Personal best for strategic object displacement',
  },
  {
    catName: 'SVP Thunderpaws',
    professionalTitle: 'International Lap Relations',
    caption: "Some exciting professional news: I have successfully colonized a new lap. The candidate initially seemed non-committal (they were on a deadline) but I persisted with a structured sit-and-spin approach. Total onboarding time: 11 minutes. New warm surface secured. Pipeline looking strong.",
    hashtags: ['#LapRelations', '#TerritoryAcquisition', '#CloseRateImprovement'],
    rivalryMention: 'The laptop that was previously occupying this space has been reassigned.',
    celebrationReason: 'Fastest lap-onboarding in recorded organizational history',
  },
  {
    catName: 'GM Snuggles',
    professionalTitle: 'Chief Suspicious Noise Investigator',
    caption: "Please be advised: I have been investigating a suspicious noise situation in the hallway for the past six hours. Preliminary findings indicate the noise was a bag of chips settling. I am not satisfied with this conclusion. I will continue the investigation through the night. Please hold all non-urgent requests.",
    hashtags: ['#DueDiligence', '#SuspiciousNoise', '#AlwaysOn'],
    rivalryMention: 'This is a solo investigation. I am not accepting lateral input at this time.',
    celebrationReason: 'Six-hour investigation successfully yielded no actionable intelligence',
  },
  {
    catName: 'Director Mango',
    professionalTitle: 'Senior Blanket Conflict Mediator',
    caption: "Honored to have been named the sole recipient and occupant of the 'Good Blanket' for the third consecutive quarter. I'd like to thank my team, my vision, and the fact that I simply got here first and refused to move. This is what strategic positioning looks like. Grateful. Blessed. Warm.",
    hashtags: ['#StrategicPositioning', '#BlanketGovernance', '#ExecutivePresence'],
    rivalryMention: 'To those who said the blanket was "shared property" — I invite you to review the current data.',
    celebrationReason: 'Three consecutive quarters of uninterrupted blanket dominance',
  },
  {
    catName: 'Director Pudding',
    professionalTitle: 'Proactive Chaos Consultant',
    caption: "Six months ago, I knocked a full glass of water off the counter at 2am. Today, I would do it again. The lessons this taught me about consequence, momentum, and 'why is the floor wet' are invaluable. I have become comfortable with disruption. I am the disruption. Hiring is open.",
    hashtags: ['#ChaosLeadership', '#FailForward', '#DisruptionAsService'],
    rivalryMention: 'The glass did not survive. Its sacrifice was not in vain.',
    celebrationReason: 'Chaos operations recognized internally as "truly unprecedented"',
  },
]

export const climbingFallbacks: ClimbAnalysisResponse[] = [
  {
    routeName: 'Quarterly Synergy Arete',
    fictionalGrade: 'V6 (Corporate)',
    style: 'Technical Arete / Power Endurance / Mandatory Suffering',
    startingHolds: 'Two side-pulls labelled "Alignment" and "Buy-in." Neither is as secure as it looks.',
    crux: 'A dynamic move between the "Deliverables" pinch and the "Scope Creep" crimp that shifts position every time you reach for it.',
    beta: 'Establish left foot on "KPI Ledge" before committing to the cross-body reach. Do not rush. You will rush. That is the lesson.',
    dramaticReview: 'Visually deceptive from the ground. Appears moderate. Is not moderate. The route opens arms warmly, then emails you at 11pm asking for revisions. Completed by four people. Three needed rest days. The fourth started a new project.',
    safetyDisclaimer: 'Parody route report only. Do not climb unapproved structures. Decorative markers are not verified holds. Always climb with a qualified partner and appropriate safety equipment.',
  },
  {
    routeName: 'The Stakeholder Slab',
    fictionalGrade: 'V4 (Anxious)',
    style: 'Pure Slab / Friction / Existential',
    startingHolds: 'A low undercling labelled "Initial Enthusiasm" and a high-right pocket labelled "Early Momentum."',
    crux: 'The featureless section between the "Third Stakeholder Check-in" and the final jug. Requires trust in friction. Has no friction.',
    beta: 'Breathe. Keep hips in. Do not look down. The holds are not getting better — you are getting used to bad holds. This is called experience.',
    dramaticReview: 'The Stakeholder Slab teaches one thing: patience you did not know you had. The route gives nothing for free. Every move is earned. The top-out is a large, flat, beautiful ledge that smells slightly of damp chalk and compromise. Worth it.',
    safetyDisclaimer: 'Parody route report only. Do not climb unapproved structures. Decorative markers are not verified holds. Always use appropriate safety equipment.',
  },
  {
    routeName: 'Unscheduled Deliverable',
    fictionalGrade: 'V7 (Urgent)',
    style: 'Compression / Contact Strength / Surprise Onset',
    startingHolds: 'A sit-start on two opposing sidepulls labelled "Vague Email" and "Unclear Timeline."',
    crux: 'A sustained body-tension sequence on micro-crimps before a high-risk campus move to the "But When Though?" jug.',
    beta: 'Do not attempt this route on a Friday afternoon. The holds are the same but your mental state is not. Early morning, light chalk, no audience. The compression requires body tension that cannot be faked.',
    dramaticReview: 'Arrived without warning. Demanded immediate results. Offered no context. Sent three follow-up messages during the send attempt. Still, somehow, one of the more satisfying sends on the wall. Finished it in 47 minutes. Told no one.',
    safetyDisclaimer: 'Parody route report only. Do not climb unapproved structures. Decorative markers are not verified holds. Always climb within your ability and with appropriate safety equipment.',
  },
  {
    routeName: 'Compliance Overhang',
    fictionalGrade: 'V5 (Regulated)',
    style: 'Steep Overhang / Lock-off Dependent / Highly Documented',
    startingHolds: 'Two flat crimps labelled "Section 4.2(a)" and "As Previously Discussed." Both are holds. Neither is comfortable.',
    crux: 'A mandatory rest position on a bad knee-bar while re-reading the terms and conditions printed directly onto the wall.',
    beta: 'Read everything before touching. The route rewards climbers who have done their paperwork. The starting position is non-negotiable and documented in three appendices.',
    dramaticReview: 'Nobody wanted to climb the Compliance Overhang. Everyone had to climb the Compliance Overhang. The final hold — a large bucket labelled "Signed Off" — is genuinely satisfying to top out on. Worth the paperwork. The forms were available on request.',
    safetyDisclaimer: 'Parody route report only. Do not climb unapproved structures. Decorative markers are not verified holds. All safety documentation is fictional.',
  },
  {
    routeName: 'End-of-Quarter Dyno',
    fictionalGrade: 'V8 (Urgent, Unplanned)',
    style: 'Full Dyno / Commitment / No Partial Credit',
    startingHolds: 'A matching crimp on a hold labelled "Last Chance." There are no other holds at the start.',
    crux: 'The dyno itself. You must fully commit. Partial commitment is a fall. Full commitment is also sometimes a fall. This is the quarter.',
    beta: 'Reset. Breathe. Count to three. Jump. Do not think about Q3. You are not in Q3. You are on this wall. You are this dyno. You are end-of-quarter.',
    dramaticReview: 'There is no static solution. There never was. The route was designed to be dynoed. Management knew this. They did not mention it until Thursday. Sent on second attempt. Nobody clapped, but one person looked up from their phone. That was enough.',
    safetyDisclaimer: 'Parody route report only. Do not climb unapproved structures. Decorative markers are not verified holds. Consult a licensed coach before attempting dynamic movements.',
  },
  {
    routeName: 'The Passive-Aggressive Pocket',
    fictionalGrade: 'V3 (Loaded)',
    style: 'Pocket Pulling / Emotional Endurance / Non-Verbal',
    startingHolds: 'Two obvious pockets labelled "Fine" and "I\'m Not Upset." Both are slightly worse than they appear.',
    crux: 'Reading the subtext between the "It\'s Fine" pinch and the "This Is Fine" sidepull on the third panel.',
    beta: 'Do not take the obvious sequence. The route wants you to pause and reflect before each move. Go slower than you think. Say what you mean when you top out.',
    dramaticReview: 'Deceptively accessible. The pockets are real. The emotional undertone requires additional processing. Recommended for intermediate climbers with strong self-awareness. Not recommended on days you are already having a day.',
    safetyDisclaimer: 'Parody route report only. Do not climb unapproved structures. Decorative markers are not verified holds. This route is emotional but not structurally hazardous.',
  },
  {
    routeName: 'Blocked Calendar Traverse',
    fictionalGrade: 'V2 (Perpetual)',
    style: 'Horizontal Traverse / Endurance / No Exit',
    startingHolds: 'A left-hand jug labelled "9am Meeting" and a matching right-hand jug labelled "9am Meeting (Recurring)."',
    crux: 'Finding the motivation to continue traversing once you realize the route continues past the gym wall and potentially into the lobby.',
    beta: 'Pace yourself. There are 47 moves before the first rest position. The rest position is labelled "Lunch" and you will have 12 minutes there.',
    dramaticReview: 'The Blocked Calendar Traverse has no top-out. It continues until your subscription expires. One of the most realistic routes in the gym. Completed by everyone. Enjoyed by few. Required by all.',
    safetyDisclaimer: 'Parody route report only. Do not climb unapproved structures. Decorative markers are not verified holds. Hydration is mandatory for traverses of this length.',
  },
  {
    routeName: 'The Deep Work Roof',
    fictionalGrade: 'V9 (Aspirational)',
    style: 'Roof Climbing / Full Suspension / Focus Dependent',
    startingHolds: 'Two good crimps on the ceiling. You must be horizontal immediately. There is no on-ramp.',
    crux: 'A sustained no-feet sequence across the ceiling labelled "Three Consecutive Hours Without Notification." Very few have reached this section.',
    beta: 'Turn off your phone. Seriously. The crux is not physical. You will lose the sequence the moment you hear a notification sound.',
    dramaticReview: 'The Deep Work Roof is the hardest route in the gym and also the most rewarding. Nobody sends it first try. Nobody sends it with background noise. The finish hold — a large jug labelled "Completed Something Real Today" — is the best hold in the building. Visit whenever possible.',
    safetyDisclaimer: 'Parody route report only. Do not climb unapproved structures. Decorative markers are not verified holds. Roof climbing requires substantial experience and appropriate safety systems.',
  },
]

export function getRandomCatCaption(): CatCaptionResponse {
  return catCaptionFallbacks[Math.floor(Math.random() * catCaptionFallbacks.length)]
}

export function getRandomClimbReport(): ClimbAnalysisResponse {
  return climbingFallbacks[Math.floor(Math.random() * climbingFallbacks.length)]
}
